import type { Queryable } from "../db/query.ts";
type NamedParams = Record<string, string | number | null>;
const FIELDS = "id,filename,activity_date,date_only,sport,duration_sec,moving_time_sec,distance_m,avg_pace_minkm,calories,avg_hr,max_hr,avg_cadence,ascent_m,descent_m,avg_speed_ms,max_speed_ms,source,system_classification,system_explanation,manual_classification,ai_classification,ai_explanation,statistical_classification,statistical_explanation,user_feedback,user_correction_reason,final_classification,classification_method,activity_type_id,activity_name";
export function createActivitiesRepo(db: Queryable) { const repo = {
  dateRange: () => db.get("SELECT MIN(date_only) AS min_date, MAX(date_only) AS max_date FROM activities WHERE deleted_at IS NULL"),
  list: (from: string, to: string) => db.all(`SELECT ${FIELDS} FROM activities WHERE date_only BETWEEN $1 AND $2 AND deleted_at IS NULL ORDER BY activity_date DESC`, [from, to]),
  listPage: (from: string, to: string, limit: number, offset: number) => db.all(`SELECT ${FIELDS} FROM activities WHERE date_only BETWEEN $1 AND $2 AND deleted_at IS NULL ORDER BY activity_date DESC LIMIT $3 OFFSET $4`, [from, to, limit, offset]),
  byId: (id: number) => db.get(`SELECT ${FIELDS} FROM activities WHERE id=$1 AND deleted_at IS NULL`, [id]),
  summary: (from: string, to: string) => db.all("SELECT sport,COUNT(*)::int AS total_activities,ROUND((SUM(distance_m)/1000)::numeric,2) AS total_km,ROUND((SUM(duration_sec)/3600)::numeric,2) AS total_hours,SUM(calories)::int AS total_calories,ROUND(AVG(avg_hr))::int AS avg_hr,ROUND(AVG(avg_pace_minkm)::numeric,2) AS avg_pace,ROUND(SUM(ascent_m)) AS total_ascent FROM activities WHERE date_only BETWEEN $1 AND $2 AND sport IS NOT NULL AND deleted_at IS NULL GROUP BY sport ORDER BY total_km DESC", [from, to]),
  weekly: (from: string, to: string) => db.all("SELECT to_char(to_date(date_only, 'YYYY-MM-DD'), 'IYYY-\"W\"IW') AS week,COUNT(*)::int AS runs,ROUND((SUM(distance_m)/1000)::numeric,2) AS km,ROUND(AVG(avg_hr))::int AS avg_hr,ROUND(AVG(avg_pace_minkm)::numeric,2) AS avg_pace FROM activities WHERE date_only BETWEEN $1 AND $2 AND deleted_at IS NULL GROUP BY week ORDER BY week", [from, to]),
  monthly: (from: string, to: string) => db.all("SELECT substring(date_only, 1, 7) AS month,COUNT(*)::int AS runs,ROUND((SUM(distance_m)/1000)::numeric,2) AS km,ROUND(AVG(avg_hr))::int AS avg_hr,ROUND(AVG(avg_pace_minkm)::numeric,2) AS avg_pace,ROUND(SUM(ascent_m)) AS ascent FROM activities WHERE date_only BETWEEN $1 AND $2 AND deleted_at IS NULL GROUP BY month ORDER BY month", [from, to]),
  track: (id: number) => db.all("SELECT elapsed_sec,timestamp_unix,distance_m,heart_rate,speed_ms,cadence,altitude_m,temperature,power,stamina FROM track_points WHERE activity_id=$1 ORDER BY COALESCE(elapsed_sec,distance_m) ASC", [id]),
  countInRange: (from: string, to: string) => db.get<{ count: number }>("SELECT COUNT(*)::int AS count FROM activities WHERE date_only BETWEEN $1 AND $2 AND deleted_at IS NULL", [from, to]),
  trash: () => db.all("SELECT id,filename,date_only,sport,distance_m,source,deleted_at FROM activities WHERE deleted_at IS NOT NULL AND purged=false ORDER BY deleted_at DESC"),
  trashPage: (limit: number, offset: number) => db.all("SELECT id,filename,date_only,sport,distance_m,source,deleted_at FROM activities WHERE deleted_at IS NOT NULL AND purged=false ORDER BY deleted_at DESC LIMIT $1 OFFSET $2", [limit, offset]),
  trashCount: () => db.get<{ count: number }>("SELECT COUNT(*)::int AS count FROM activities WHERE deleted_at IS NOT NULL AND purged=false"),
  softDeleteRange: (from: string, to: string) => db.run("UPDATE activities SET deleted_at=to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD\"T\"HH24:MI:SS.MS\"Z\"') WHERE date_only BETWEEN $1 AND $2 AND deleted_at IS NULL", [from, to]),
  softDeleteById: (id: number) => db.run("UPDATE activities SET deleted_at=to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD\"T\"HH24:MI:SS.MS\"Z\"') WHERE id=$1 AND deleted_at IS NULL", [id]),
  restoreById: (id: number) => db.run("UPDATE activities SET deleted_at=NULL WHERE id=$1 AND purged=false", [id]),
  deleteTrackPoints: (id: number) => db.run("DELETE FROM track_points WHERE activity_id=$1", [id]),
  purgeById: (id: number) => db.run("UPDATE activities SET purged=true,distance_m=NULL,avg_pace_minkm=NULL,calories=NULL,avg_hr=NULL,max_hr=NULL,avg_cadence=NULL,ascent_m=NULL,descent_m=NULL,avg_speed_ms=NULL,max_speed_ms=NULL,moving_time_sec=NULL,duration_sec=NULL WHERE id=$1", [id]),
  updateAiClassification: (p: NamedParams) => db.run("UPDATE activities SET ai_classification=$1,ai_explanation=$2,user_feedback=NULL,user_correction_reason=NULL,final_classification=NULL,classification_method=NULL WHERE id=$3", [p.$classification, p.$explanation, p.$id]),
  updateStatisticalClassification: (p: NamedParams) => db.run("UPDATE activities SET statistical_classification=$1,statistical_explanation=$2,user_feedback=NULL,user_correction_reason=NULL,final_classification=NULL,classification_method=NULL WHERE id=$3", [p.$classification, p.$explanation, p.$id]),
  updateFeedback: (p: NamedParams) => db.run("UPDATE activities SET user_feedback=$1,user_correction_reason=$2,final_classification=$3,classification_method=$4 WHERE id=$5", [p.$user_feedback,p.$user_correction_reason,p.$final_classification,p.$classification_method,p.$id]),
  confirmById: (p: NamedParams) => db.run("UPDATE activities SET user_feedback='approved',final_classification=CASE WHEN $1='ai' THEN ai_classification ELSE statistical_classification END,classification_method=$1,user_correction_reason=NULL WHERE id=$2 AND (CASE WHEN $1='ai' THEN ai_classification ELSE statistical_classification END) IS NOT NULL", [p.$source,p.$id]),
  updateType: (p: NamedParams) => db.run("UPDATE activities SET activity_type_id=$1,activity_name=$2 WHERE id=$3", [p.$activity_type_id,p.$activity_name,p.$id]),
  races: (limit: number, offset: number) => db.all("SELECT id,date_only,activity_type_id,activity_name,distance_m FROM activities WHERE activity_type_id!=1 AND deleted_at IS NULL ORDER BY date_only DESC LIMIT $1 OFFSET $2", [limit,offset]),
  racesCount: () => db.get<{ count: number }>("SELECT COUNT(*)::int AS count FROM activities WHERE activity_type_id!=1 AND deleted_at IS NULL"),
  runningActivitiesForAssociation: () => db.all<{ id: number; activity_date: string }>("SELECT id,activity_date FROM activities WHERE sport='running' AND deleted_at IS NULL"),
  // HRA-370: bounded, most-recent-first activities for one owner, used only by
  // the authenticated publication orchestrator to build a public projection
  // input — never by any owner-facing list view (those use list/listPage above).
  recentForPublication: (userId: string, limit: number) => db.all(`SELECT ${FIELDS} FROM activities WHERE user_id=$1 AND deleted_at IS NULL ORDER BY activity_date DESC LIMIT $2`, [userId, limit]),
}; return { ...repo, withDb: (query: Queryable) => createActivitiesRepo(query) }; }
export type ActivitiesRepo = ReturnType<typeof createActivitiesRepo>;
