import type { PlanInstanceDayRow, PlanInstanceRow } from "../db.ts";
import type { Queryable } from "../db/query.ts";
import type { PlanInstanceDayInput, PlanInstanceInput } from "./plan-instances.repo.ts";

const DF = "d.id,d.instance_id,w.section_name,w.week_number,d.date,w.day,w.suffix,w.category,w.workout_type,w.segments::text AS segments,w.activity_target::text AS activity_target,w.activity_description,w.notes,w.needs_review,d.scheduled_time,w.customized_at,d.workout_id";
const DAYS = " FROM plan_instance_days d JOIN plan_instance_workouts w ON w.instance_id=d.instance_id AND w.workout_id=d.workout_id JOIN plan_instances pi ON pi.id=d.instance_id";
const IF = "id,template_id,start_date,pace_overrides::text AS pace_overrides,target_activity_id,approved_at,name,event,race_name,race_date,race_url,schedule_timezone,original_start_date,original_days_snapshot::text AS original_days_snapshot,current_revision,original_revision,created_at";

export function createOwnedPlanInstancesRepo(db: Queryable, userId: string) {
  const repo = {
    instanceById: (id: number) => db.get<PlanInstanceRow>(`SELECT ${IF} FROM plan_instances WHERE user_id=$1 AND id=$2`, [userId, id]),
    daysByInstance: (id: number) => db.all<PlanInstanceDayRow>(`SELECT ${DF}${DAYS} WHERE pi.user_id=$1 AND d.instance_id=$2 ORDER BY d.date,w.day`, [userId, id]),
    allInstances: () => db.all<PlanInstanceRow>(`SELECT ${IF} FROM plan_instances WHERE user_id=$1 ORDER BY created_at DESC`, [userId]),
    dayByWorkoutId: (workoutId: string) => db.get<PlanInstanceDayRow & { instance_name: string | null }>(`SELECT ${DF},pi.name instance_name${DAYS} WHERE pi.user_id=$1 AND d.workout_id=$2`, [userId, workoutId]),
    runDaysWithTimezone: () => db.all<{workout_id:string;date:string;schedule_timezone:string|null;instance_id:number}>(`SELECT d.workout_id,d.date,pi.schedule_timezone,d.instance_id${DAYS} WHERE pi.user_id=$1 AND w.workout_type='run'`, [userId]),
    listPage: (limit:number, offset:number, templateId?:number) => db.all<PlanInstanceRow>(`SELECT ${IF} FROM plan_instances WHERE user_id=$1${templateId == null ? "" : " AND template_id=$2"} ORDER BY created_at DESC LIMIT $${templateId == null ? 2 : 3} OFFSET $${templateId == null ? 3 : 4}`, templateId == null ? [userId,limit,offset] : [userId,templateId,limit,offset]),
    count: (templateId?:number) => db.get<{count:number}>(`SELECT COUNT(*)::int count FROM plan_instances WHERE user_id=$1${templateId == null ? "" : " AND template_id=$2"}`, templateId == null ? [userId] : [userId,templateId]),
    daysBySection: (id:number, section:string) => db.all<PlanInstanceDayRow>(`SELECT ${DF}${DAYS} WHERE pi.user_id=$1 AND d.instance_id=$2 AND w.section_name=$3 ORDER BY d.date,w.day`, [userId,id,section]),
    daysBySectionAndWeek: (id:number, section:string, week:number) => db.all<PlanInstanceDayRow>(`SELECT ${DF}${DAYS} WHERE pi.user_id=$1 AND d.instance_id=$2 AND w.section_name=$3 AND w.week_number=$4 ORDER BY d.date,w.day`, [userId,id,section,week]),
    dayById: (id:number) => db.get<PlanInstanceDayRow>(`SELECT ${DF}${DAYS} WHERE pi.user_id=$1 AND d.id=$2`, [userId,id]),
    daysByDateAndWorkoutType: (date:string,type:string) => db.all<PlanInstanceDayRow & { instance_name:string|null }>(`SELECT ${DF},pi.name instance_name${DAYS} WHERE pi.user_id=$1 AND d.date=$2 AND w.workout_type=$3 ORDER BY pi.created_at DESC`,[userId,date,type]),
    activeInstanceIdForDate: async (date:string) => (await db.get<{id:number}>(`SELECT pi.id FROM plan_instance_days d JOIN plan_instances pi ON pi.id=d.instance_id WHERE pi.user_id=$1 AND d.date=$2 AND pi.approved_at IS NOT NULL ORDER BY pi.created_at DESC LIMIT 1`,[userId,date]))?.id,
    createInstance: (i:PlanInstanceInput) => db.get<PlanInstanceRow>(`INSERT INTO plan_instances (user_id,template_id,start_date,pace_overrides,target_activity_id,name,event,race_name,race_date,race_url,schedule_timezone,original_start_date,original_days_snapshot) SELECT $1,$2,$3,$4::jsonb,$5::bigint,$6,$7,$8,$9,$10,$11,$12,$13::jsonb WHERE EXISTS (SELECT 1 FROM plan_templates WHERE id=$2 AND user_id=$1) AND ($5::bigint IS NULL OR EXISTS (SELECT 1 FROM activities WHERE id=$5::bigint AND user_id=$1)) RETURNING ${IF}`,[userId,i.template_id,i.start_date,i.pace_overrides,i.target_activity_id,i.name,i.event,i.race_name,i.race_date,i.race_url,i.schedule_timezone,i.original_start_date,i.original_days_snapshot]),
    async createDay(d:PlanInstanceDayInput) { await db.run(`INSERT INTO plan_instance_workouts (instance_id,workout_id,user_id,section_name,week_number,day,suffix,category,workout_type,segments,activity_target,activity_description,notes,needs_review,customized_at) SELECT $1,$2,$3,$4,$5,$6,$7,$8,$9,$10::jsonb,$11,$12,$13,$14::boolean,$15 FROM plan_instances WHERE id=$1 AND user_id=$3 ON CONFLICT (instance_id,workout_id) DO UPDATE SET section_name=excluded.section_name,week_number=excluded.week_number,day=excluded.day,suffix=excluded.suffix,category=excluded.category,workout_type=excluded.workout_type,segments=excluded.segments,activity_target=excluded.activity_target,activity_description=excluded.activity_description,notes=excluded.notes,needs_review=excluded.needs_review,customized_at=excluded.customized_at`,[d.instance_id,d.workout_id,userId,d.section_name,d.week_number,d.day,d.suffix,d.category,d.workout_type,d.segments,d.activity_target,d.activity_description,d.notes,d.needs_review,d.customized_at]); await db.run(`INSERT INTO plan_instance_days (instance_id,workout_id,user_id,date,scheduled_time) SELECT $1,$2,$3,$4,$5 WHERE EXISTS (SELECT 1 FROM plan_instances WHERE id=$1 AND user_id=$3)`,[d.instance_id,d.workout_id,userId,d.date,d.scheduled_time]); },
    deleteDaysByInstance:(id:number)=>db.run("DELETE FROM plan_instance_days d USING plan_instances pi WHERE d.instance_id=pi.id AND pi.user_id=$1 AND d.instance_id=$2",[userId,id]),
    dayByIdentity:async(instanceId:number,section:string,week:number,day:number)=>(await db.get<{workout_id:string}>(`SELECT w.workout_id${DAYS} WHERE pi.user_id=$1 AND d.instance_id=$2 AND w.section_name=$3 AND w.week_number=$4 AND w.day=$5`,[userId,instanceId,section,week,day]))?.workout_id,
    deleteDayByIdentity:(id:number,section:string,week:number,day:number)=>db.run(`DELETE FROM plan_instance_days d USING plan_instance_workouts w, plan_instances pi WHERE d.instance_id=w.instance_id AND d.workout_id=w.workout_id AND pi.id=d.instance_id AND pi.user_id=$1 AND d.instance_id=$2 AND w.section_name=$3 AND w.week_number=$4 AND w.day=$5`,[userId,id,section,week,day]),
    clearApproval:(id:number)=>db.run("UPDATE plan_instances SET approved_at=NULL WHERE user_id=$1 AND id=$2",[userId,id]),
    async updateFields(id:number,f:Partial<{name:string;race_name:string|null;race_date:string|null;race_url:string|null}>) { const fields: string[]=[]; const values:unknown[]=[]; for(const [column,value] of Object.entries(f)){if(value!==undefined){values.push(value);fields.push(`${column}=$${values.length+2}`)}} if(fields.length) await db.run(`UPDATE plan_instances SET ${fields.join(",")} WHERE user_id=$1 AND id=$2`,[userId,id,...values]); },
    updateStartDateAndPaceOverrides:(id:number,start:string,pace:string|null)=>db.run("UPDATE plan_instances SET start_date=$3,pace_overrides=$4::jsonb WHERE user_id=$1 AND id=$2",[userId,id,start,pace]),
    updateScheduleTimezone:(id:number,tz:string)=>db.run("UPDATE plan_instances SET schedule_timezone=$3 WHERE user_id=$1 AND id=$2",[userId,id,tz]),
    updateOriginal:(id:number,start:string,snapshot:string,revision:number)=>db.run("UPDATE plan_instances SET original_start_date=$3,original_days_snapshot=$4::jsonb,original_revision=$5 WHERE user_id=$1 AND id=$2",[userId,id,start,snapshot,revision]),
    bumpCurrentRevision:(id:number)=>db.run("UPDATE plan_instances SET current_revision=current_revision+1 WHERE user_id=$1 AND id=$2",[userId,id]),
    updateDayFromDsl:(id:number,d: {day:number;suffix:string|null;category:string|null;workout_type:string;segments:string;activity_target:string|null;activity_description:string|null;notes:string|null;needs_review:number})=>db.run(`UPDATE plan_instance_workouts w SET day=$3,suffix=$4,category=$5,workout_type=$6,segments=$7::jsonb,activity_target=$8,activity_description=$9,notes=$10,needs_review=$11::boolean FROM plan_instance_days d, plan_instances pi WHERE d.instance_id=w.instance_id AND d.workout_id=w.workout_id AND pi.id=d.instance_id AND pi.user_id=$1 AND d.id=$2`,[userId,id,d.day,d.suffix,d.category,d.workout_type,d.segments,d.activity_target,d.activity_description,d.notes,d.needs_review]),
    updateDayNotes:(id:number,notes:string|null)=>db.run(`UPDATE plan_instance_workouts w SET notes=$3 FROM plan_instance_days d, plan_instances pi WHERE d.instance_id=w.instance_id AND d.workout_id=w.workout_id AND pi.id=d.instance_id AND pi.user_id=$1 AND d.id=$2`,[userId,id,notes]),
    updateDayScheduledTime:(id:number,time:string|null)=>db.run("UPDATE plan_instance_days d SET scheduled_time=$3 FROM plan_instances pi WHERE pi.id=d.instance_id AND pi.user_id=$1 AND d.id=$2",[userId,id,time]),
    updateDayWorkoutId:(id:number,workoutId:string)=>db.run("UPDATE plan_instance_days d SET workout_id=$3 FROM plan_instances pi WHERE pi.id=d.instance_id AND pi.user_id=$1 AND d.id=$2",[userId,id,workoutId]),
    deferConstraints:()=>db.run("SET CONSTRAINTS ALL DEFERRED"), deferWorkoutIdentityConstraint:()=>db.run("SET CONSTRAINTS plan_instance_days_instance_id_workout_id_key DEFERRED"),
    lockDaysForSwap:(a:number,b:number)=>db.all<{id:number;instance_id:number;workout_id:string}>("SELECT d.id,d.instance_id,d.workout_id FROM plan_instance_days d JOIN plan_instances pi ON pi.id=d.instance_id WHERE pi.user_id=$1 AND d.id IN ($2,$3) FOR UPDATE",[userId,a,b]),
    swapWorkoutIds:(a:number,wa:string,b:number,wb:string)=>db.run("UPDATE plan_instance_days d SET workout_id=CASE d.id WHEN $2 THEN $3 WHEN $4 THEN $5 END FROM plan_instances pi WHERE pi.id=d.instance_id AND pi.user_id=$1 AND d.id IN ($2,$4)",[userId,a,wa,b,wb]),
    markDayCustomized:(id:number)=>db.run(`UPDATE plan_instance_workouts w SET customized_at=to_char(now() AT TIME ZONE 'UTC','YYYY-MM-DD\"T\"HH24:MI:SS.MS\"Z\"') FROM plan_instance_days d,plan_instances pi WHERE d.instance_id=w.instance_id AND d.workout_id=w.workout_id AND pi.id=d.instance_id AND pi.user_id=$1 AND d.id=$2`,[userId,id]),
    customizedDaysFrom:(id:number,from:string)=>db.all<PlanInstanceDayRow>(`SELECT ${DF}${DAYS} WHERE pi.user_id=$1 AND d.instance_id=$2 AND d.date >= $3 AND w.customized_at IS NOT NULL ORDER BY d.date,w.day`,[userId,id,from]),
    approve:(id:number)=>db.get<PlanInstanceRow>(`UPDATE plan_instances SET approved_at=to_char(now() AT TIME ZONE 'UTC','YYYY-MM-DD\"T\"HH24:MI:SS.MS\"Z\"') WHERE user_id=$1 AND id=$2 RETURNING ${IF}`,[userId,id]),
    async dateRangeForInstance(id:number){const r=await db.get<{start_date:string|null;end_date:string|null}>("SELECT MIN(d.date) start_date,MAX(d.date) end_date FROM plan_instance_days d JOIN plan_instances pi ON pi.id=d.instance_id WHERE pi.user_id=$1 AND d.instance_id=$2",[userId,id]);return r?.start_date&&r.end_date?{start_date:r.start_date,end_date:r.end_date}:undefined;},
    overlappingApproved:(id:number,start:string,end:string)=>db.all<{id:number;name:string|null;start_date:string;end_date:string}>("SELECT pi.id,pi.name,MIN(d.date) start_date,MAX(d.date) end_date FROM plan_instances pi JOIN plan_instance_days d ON d.instance_id=pi.id WHERE pi.user_id=$1 AND pi.approved_at IS NOT NULL AND pi.id != $2 GROUP BY pi.id HAVING MAX(d.date)>=$3 AND MIN(d.date)<=$4",[userId,id,start,end]),
    remove:(id:number)=>db.run("DELETE FROM plan_instances WHERE user_id=$1 AND id=$2",[userId,id]),
  };
  return { ...repo, withDb: (query: Queryable) => createOwnedPlanInstancesRepo(query, userId) };
}
