-- PostgreSQL is the local runtime database. This file is intentionally the
-- complete initial schema: application startup never repairs it.

CREATE TABLE users (
  id UUID PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE external_identities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  issuer TEXT NOT NULL,
  subject TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (issuer, subject)
);

CREATE TABLE activity_types (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  min_distance_m DOUBLE PRECISION NOT NULL DEFAULT 0
);

CREATE TABLE activities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  filename TEXT NOT NULL,
  activity_date TEXT NOT NULL,
  date_only TEXT NOT NULL,
  sport TEXT,
  duration_sec DOUBLE PRECISION,
  distance_m DOUBLE PRECISION,
  avg_pace_minkm DOUBLE PRECISION,
  calories INTEGER,
  avg_hr INTEGER,
  max_hr INTEGER,
  avg_cadence INTEGER,
  ascent_m DOUBLE PRECISION,
  descent_m DOUBLE PRECISION,
  avg_speed_ms DOUBLE PRECISION,
  max_speed_ms DOUBLE PRECISION,
  source TEXT NOT NULL DEFAULT 'garmin',
  moving_time_sec DOUBLE PRECISION,
  imported_at TIMESTAMPTZ DEFAULT now(),
  deleted_at TEXT,
  purged BOOLEAN NOT NULL DEFAULT false,
  ai_classification TEXT,
  ai_explanation TEXT,
  statistical_classification TEXT,
  statistical_explanation TEXT,
  user_feedback TEXT,
  user_correction_reason TEXT,
  final_classification TEXT,
  classification_method TEXT,
  activity_type_id INTEGER NOT NULL DEFAULT 1 REFERENCES activity_types(id),
  activity_name TEXT,
  UNIQUE (user_id, filename),
  UNIQUE (id, user_id)
);

CREATE TABLE track_points (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  activity_id BIGINT NOT NULL REFERENCES activities(id) ON DELETE CASCADE,
  elapsed_sec DOUBLE PRECISION,
  timestamp_unix BIGINT,
  distance_m DOUBLE PRECISION,
  heart_rate INTEGER,
  speed_ms DOUBLE PRECISION,
  cadence INTEGER,
  altitude_m DOUBLE PRECISION,
  temperature INTEGER,
  power INTEGER,
  lat DOUBLE PRECISION,
  lon DOUBLE PRECISION,
  stamina INTEGER
);

CREATE TABLE body_measurements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  measured_at TEXT NOT NULL,
  date_only TEXT NOT NULL,
  weight_kg DOUBLE PRECISION,
  fat_ratio DOUBLE PRECISION,
  fat_mass_kg DOUBLE PRECISION,
  muscle_mass_kg DOUBLE PRECISION,
  hydration_kg DOUBLE PRECISION,
  bone_mass_kg DOUBLE PRECISION,
  bmi DOUBLE PRECISION,
  heart_rate INTEGER,
  deleted_at TEXT,
  purged BOOLEAN NOT NULL DEFAULT false,
  UNIQUE (user_id, measured_at)
);

CREATE TABLE user_settings (
  user_id UUID PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  outlier_speed_delta_per_sec DOUBLE PRECISION NOT NULL DEFAULT 2.0,
  outlier_cadence_delta_per_sec DOUBLE PRECISION NOT NULL DEFAULT 60.0,
  outlier_min_speed_kmh DOUBLE PRECISION NOT NULL DEFAULT 6.0,
  theme TEXT NOT NULL DEFAULT 'auto',
  background_kind TEXT NOT NULL DEFAULT 'none',
  background_value TEXT,
  unit_system TEXT NOT NULL DEFAULT 'auto',
  timezone TEXT,
  min_trend_group_size INTEGER NOT NULL DEFAULT 5,
  activity_detail_view TEXT NOT NULL DEFAULT 'accordion',
  accent_color TEXT NOT NULL DEFAULT 'sky',
  date_format TEXT NOT NULL DEFAULT 'literal_uk',
  language TEXT NOT NULL DEFAULT 'auto',
  palette TEXT NOT NULL DEFAULT 'auto',
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- Temporary per-user connection storage. Provider-account modelling remains
-- deferred; these tables deliberately do not implement Auth0 or sync redesign.
CREATE TABLE withings_tokens (
  user_id UUID PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  access_token TEXT NOT NULL,
  refresh_token TEXT NOT NULL,
  expires_at BIGINT NOT NULL,
  scope TEXT,
  updated_at TIMESTAMPTZ DEFAULT now()
);
CREATE TABLE strava_tokens (
  user_id UUID PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  access_token TEXT NOT NULL,
  refresh_token TEXT NOT NULL,
  expires_at BIGINT NOT NULL,
  scope TEXT,
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE date_ranges (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  from_date TEXT NOT NULL,
  to_date TEXT NOT NULL,
  activity_id BIGINT,
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE (user_id, name),
  FOREIGN KEY (activity_id, user_id) REFERENCES activities(id, user_id)
);

CREATE TABLE plan_templates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  dsl_source TEXT NOT NULL,
  parsed_plan JSONB NOT NULL,
  event TEXT,
  approved_at TEXT,
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE (id, user_id)
);

CREATE TABLE plan_instances (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  template_id BIGINT NOT NULL,
  start_date TEXT NOT NULL,
  pace_overrides JSONB,
  target_activity_id BIGINT,
  approved_at TEXT,
  name TEXT,
  event TEXT,
  race_name TEXT,
  race_date TEXT,
  race_url TEXT,
  schedule_timezone TEXT,
  original_start_date TEXT,
  original_days_snapshot JSONB,
  current_revision INTEGER NOT NULL DEFAULT 1,
  original_revision INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE (id, user_id),
  FOREIGN KEY (template_id, user_id) REFERENCES plan_templates(id, user_id) ON DELETE CASCADE,
  FOREIGN KEY (target_activity_id, user_id) REFERENCES activities(id, user_id)
);

CREATE TABLE plan_instance_workouts (
  instance_id BIGINT NOT NULL,
  workout_id TEXT NOT NULL,
  user_id UUID NOT NULL,
  section_name TEXT NOT NULL,
  week_number INTEGER NOT NULL,
  day INTEGER NOT NULL,
  suffix TEXT,
  category TEXT,
  workout_type TEXT NOT NULL,
  segments JSONB NOT NULL,
  activity_target TEXT,
  activity_description TEXT,
  notes TEXT,
  needs_review BOOLEAN NOT NULL DEFAULT false,
  customized_at TEXT,
  created_at TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY (instance_id, workout_id),
  UNIQUE (instance_id, workout_id) DEFERRABLE INITIALLY IMMEDIATE,
  FOREIGN KEY (instance_id, user_id) REFERENCES plan_instances(id, user_id) ON DELETE CASCADE
);

CREATE TABLE plan_instance_days (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  instance_id BIGINT NOT NULL,
  workout_id TEXT NOT NULL,
  user_id UUID NOT NULL,
  date TEXT NOT NULL,
  scheduled_time TEXT,
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE (instance_id, workout_id) DEFERRABLE INITIALLY IMMEDIATE,
  FOREIGN KEY (instance_id, user_id) REFERENCES plan_instances(id, user_id) ON DELETE CASCADE,
  FOREIGN KEY (instance_id, workout_id) REFERENCES plan_instance_workouts(instance_id, workout_id)
);

CREATE TABLE workout_associations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  activity_id BIGINT NOT NULL,
  instance_id BIGINT,
  workout_id TEXT,
  status TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE (activity_id),
  FOREIGN KEY (activity_id, user_id) REFERENCES activities(id, user_id) ON DELETE CASCADE,
  FOREIGN KEY (instance_id, user_id) REFERENCES plan_instances(id, user_id),
  FOREIGN KEY (instance_id, workout_id) REFERENCES plan_instance_workouts(instance_id, workout_id),
  CHECK ((instance_id IS NULL AND workout_id IS NULL) OR (instance_id IS NOT NULL AND workout_id IS NOT NULL))
);

CREATE TABLE workout_segment_alignments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  association_id BIGINT NOT NULL REFERENCES workout_associations(id) ON DELETE CASCADE,
  segment_index INTEGER NOT NULL,
  distance_m DOUBLE PRECISION,
  duration_sec DOUBLE PRECISION,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE (association_id, segment_index)
);

CREATE TABLE feedback (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  free_text TEXT,
  pricing_choice TEXT,
  pricing_why_not_free_text TEXT,
  feature_interest JSONB,
  feature_interest_other_free_text TEXT,
  app_type_choice TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX idx_activities_user_date ON activities(user_id, date_only);
CREATE INDEX idx_track_activity ON track_points(activity_id);
CREATE INDEX idx_body_user_date ON body_measurements(user_id, date_only);
CREATE INDEX idx_plan_instances_user_template ON plan_instances(user_id, template_id);
CREATE INDEX idx_plan_instance_days_instance_date ON plan_instance_days(instance_id, date);
CREATE INDEX idx_workout_associations_workout ON workout_associations(instance_id, workout_id);

INSERT INTO activity_types (id, name, min_distance_m) VALUES
  (1, 'Training', 0),
  (2, 'Race 5km', 5000),
  (3, 'Race 10km', 10000),
  (4, 'Half-Marathon', 21097.5),
  (5, 'Marathon', 42195)
ON CONFLICT (id) DO NOTHING;
SELECT setval(pg_get_serial_sequence('activity_types', 'id'), 5, true);
