-- HRA-348: internal user + external-identity domain, per
-- docs/architecture/AUTHENTICATION-TENANCY-ADR.md. Persistence/domain models only —
-- no login/callback HTTP routes are introduced by this migration.

ALTER TABLE users
  ADD COLUMN display_name TEXT,
  ADD COLUMN locale TEXT,
  ADD COLUMN unit_system TEXT CHECK (unit_system IN ('metric', 'imperial')),
  ADD COLUMN timezone TEXT,
  ADD COLUMN status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'disabled', 'deletion_pending')),
  ADD COLUMN role TEXT NOT NULL DEFAULT 'user' CHECK (role IN ('user', 'admin')),
  ADD COLUMN updated_at TIMESTAMPTZ NOT NULL DEFAULT now();

-- provider/email are non-authoritative metadata (AC2): informational only,
-- never used to look up or merge a user. Lookup is always by (issuer, subject).
ALTER TABLE external_identities
  ADD COLUMN provider TEXT,
  ADD COLUMN email_at_link_time TEXT,
  ADD COLUMN updated_at TIMESTAMPTZ NOT NULL DEFAULT now();

-- Feature/subscription capabilities, deliberately separate from users.role
-- (AC9) so entitlements can be granted/revoked without touching the role
-- boundary that gates admin-only application surfaces.
CREATE TABLE user_entitlements (
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  entitlement TEXT NOT NULL,
  granted_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, entitlement)
);

-- Opaque session state (AC6): `id` is a non-secret lookup key, `secret_hash`
-- is a SHA-256 digest of the real bearer secret — the raw secret itself is
-- never persisted, only ever held by the caller (cookie/verifier). Idle and
-- absolute expiry are tracked independently so idle renewal can never extend
-- a session past its absolute lifetime (ADR: 30 min idle / 12h absolute).
CREATE TABLE sessions (
  id UUID PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  secret_hash TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  idle_expires_at TIMESTAMPTZ NOT NULL,
  absolute_expires_at TIMESTAMPTZ NOT NULL,
  revoked_at TIMESTAMPTZ
);
CREATE INDEX idx_sessions_user ON sessions(user_id);

-- Minimum useful authentication/session lifecycle facts (AC13). `detail` is a
-- short non-sensitive label; this table must never receive credentials,
-- provider tokens, raw FIT data, or training payloads.
CREATE TABLE security_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_type TEXT NOT NULL,
  user_id UUID REFERENCES users(id) ON DELETE SET NULL,
  external_issuer TEXT,
  external_subject TEXT,
  detail TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_security_events_user ON security_events(user_id);
CREATE INDEX idx_security_events_type_created ON security_events(event_type, created_at);
