-- HRA-352: owner-scoped integration credentials, OAuth callback state, and
-- sync job locking. Provider token rows already carry user_id as their PK
-- (001_postgresql_foundation.sql) — this migration adds what was still
-- missing: a provider-account identifier (to detect the same external
-- account being linked by two different Runs Free users), a real
-- server-side OAuth state store (replacing the in-memory singleton in
-- http/oauth.ts), and a per-owner sync run lock.

ALTER TABLE withings_tokens ADD COLUMN provider_account_id TEXT;
ALTER TABLE strava_tokens   ADD COLUMN provider_account_id TEXT;

-- Partial unique index (NULLs excluded) — enforces "one provider account
-- links to at most one Runs Free user" at the database level without
-- rejecting rows where the account id isn't known yet.
CREATE UNIQUE INDEX idx_withings_tokens_provider_account ON withings_tokens(provider_account_id) WHERE provider_account_id IS NOT NULL;
CREATE UNIQUE INDEX idx_strava_tokens_provider_account   ON strava_tokens(provider_account_id)   WHERE provider_account_id IS NOT NULL;

-- OAuth callback state (AC3/AC4): minted only for an authenticated user,
-- transaction-bound to (user, provider, redirect_uri), single-use
-- (consumed_at), expiring. Every failure mode at the callback (missing,
-- expired, already-consumed, wrong provider) collapses to the same
-- outcome — see http/oauth.ts's consumeOauthState.
CREATE TABLE oauth_states (
  token TEXT PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  provider TEXT NOT NULL,
  redirect_uri TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  expires_at TIMESTAMPTZ NOT NULL,
  consumed_at TIMESTAMPTZ
);
CREATE INDEX idx_oauth_states_expires ON oauth_states(expires_at);

-- Per-owner sync run record + lock (AC7/AC8): the partial unique index below
-- is the lock itself — a second sync for the same (user, provider) while one
-- is still 'running' hits a unique violation instead of racing the first.
CREATE TABLE sync_runs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  provider TEXT NOT NULL CHECK (provider IN ('garmin', 'withings', 'strava')),
  status TEXT NOT NULL CHECK (status IN ('running', 'succeeded', 'failed')) DEFAULT 'running',
  started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  finished_at TIMESTAMPTZ,
  imported INTEGER,
  skipped INTEGER,
  errors INTEGER,
  error_message TEXT
);
CREATE UNIQUE INDEX idx_sync_runs_active ON sync_runs(user_id, provider) WHERE status = 'running';
CREATE INDEX idx_sync_runs_user_provider ON sync_runs(user_id, provider, started_at DESC);
